language: node_js
node_js:
  - "4.1"

install:
- npm install
- gem update --system
- gem install jekyll

script:
- npm run build
- npm run accessibility

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - gh-pages
