language: ruby
rvm:
- 2.1

node_js:
- "4.1"

install:
- npm install
- gem install jekyll

script:
- npm run build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - gh-pages
